// src/demos/320-multiple-swipers/vue/src/App.vue
<template>
  <swiper
    :spaceBetween="30"
    :pagination="{
      clickable: true,
    }"
    :modules="modules"
    class="mySwiper"
  >
    <swiper-slide>Slide 1</swiper-slide><swiper-slide>Slide 2</swiper-slide
    ><swiper-slide>Slide 3</swiper-slide><swiper-slide>Slide 4</swiper-slide
    ><swiper-slide>Slide 5</swiper-slide><swiper-slide>Slide 6</swiper-slide
    ><swiper-slide>Slide 7</swiper-slide><swiper-slide>Slide 8</swiper-slide
    ><swiper-slide>Slide 9</swiper-slide> </swiper
  ><swiper
    :spaceBetween="30"
    :pagination="{
      clickable: true,
    }"
    :modules="modules"
    class="mySwiper2"
  >
    <swiper-slide>Slide 1</swiper-slide><swiper-slide>Slide 2</swiper-slide
    ><swiper-slide>Slide 3</swiper-slide><swiper-slide>Slide 4</swiper-slide
    ><swiper-slide>Slide 5</swiper-slide><swiper-slide>Slide 6</swiper-slide
    ><swiper-slide>Slide 7</swiper-slide><swiper-slide>Slide 8</swiper-slide
    ><swiper-slide>Slide 9</swiper-slide> </swiper
  ><swiper
    :spaceBetween="30"
    :pagination="{
      clickable: true,
    }"
    :modules="modules"
    class="mySwiper3"
  >
    <swiper-slide>Slide 1</swiper-slide><swiper-slide>Slide 2</swiper-slide
    ><swiper-slide>Slide 3</swiper-slide><swiper-slide>Slide 4</swiper-slide
    ><swiper-slide>Slide 5</swiper-slide><swiper-slide>Slide 6</swiper-slide
    ><swiper-slide>Slide 7</swiper-slide><swiper-slide>Slide 8</swiper-slide
    ><swiper-slide>Slide 9</swiper-slide>
  </swiper>
</template>
<script>
// Import Swiper Vue.js components
import { Swiper, SwiperSlide } from "swiper/vue";

// Import Swiper styles
import "swiper/css";

import "swiper/css/pagination";

import "./style.css";

// import required modules
import { Pagination } from "swiper";

export default {
  components: {
    Swiper,
    SwiperSlide,
  },
  setup() {
    return {
      modules: [Pagination],
    };
  },
};
</script>

// src/demos/180-nested/svelte/App.svelte
<script>
  import { Swiper, SwiperSlide } from "swiper/svelte";

  // Import Swiper styles
  import "swiper/css";

  import "swiper/css/pagination";

  import "./style.css";

  // import required modules
  import { Pagination } from "swiper";
</script>

<Swiper
  class="mySwiper swiper-h"
  spaceBetween={50}
  pagination={{
    clickable: true,
  }}
  modules={[Pagination]}
>
  <SwiperSlide>Horizontal Slide 1</SwiperSlide>
  <SwiperSlide>
    <Swiper
      class="mySwiper2 swiper-v"
      direction={"vertical"}
      spaceBetween={50}
      pagination={{
        clickable: true,
      }}
      modules={[Pagination]}
    >
      <SwiperSlide>Vertical Slide 1</SwiperSlide>
      <SwiperSlide>Vertical Slide 2</SwiperSlide>
      <SwiperSlide>Vertical Slide 3</SwiperSlide>
      <SwiperSlide>Vertical Slide 4</SwiperSlide>
      <SwiperSlide>Vertical Slide 5</SwiperSlide>
    </Swiper>
  </SwiperSlide>
  <SwiperSlide>Horizontal Slide 3</SwiperSlide>
  <SwiperSlide>Horizontal Slide 4</SwiperSlide>
</Swiper>
