// src/demos/300-thumbs-gallery/angular/src/app/app.component.ts
import { Component, ViewEncapsulation, ViewChild } from "@angular/core";
import { SwiperComponent } from "swiper/angular";

// import Swiper core and required modules
import SwiperCore, { FreeMode, Navigation, Thumbs } from "swiper";

// install Swiper modules
SwiperCore.use([FreeMode, Navigation, Thumbs]);

@Component({
  selector: "app-swiper-example",
  template: ` <swiper
      style="--swiper-navigation-color: #fff;--swiper-pagination-color: #fff"
      [spaceBetween]="10"
      [navigation]="true"
      [thumbs]="{ swiper: thumbsSwiper }"
      class="mySwiper2"
    >
      <ng-template swiperSlide
        ><img
          src="https://swiperjs.com/demos/images/nature-1.jpg" /></ng-template
      ><ng-template swiperSlide
        ><img
          src="https://swiperjs.com/demos/images/nature-2.jpg" /></ng-template
      ><ng-template swiperSlide
        ><img
          src="https://swiperjs.com/demos/images/nature-3.jpg" /></ng-template
      ><ng-template swiperSlide
        ><img
          src="https://swiperjs.com/demos/images/nature-4.jpg" /></ng-template
      ><ng-template swiperSlide
        ><img
          src="https://swiperjs.com/demos/images/nature-5.jpg" /></ng-template
      ><ng-template swiperSlide
        ><img
          src="https://swiperjs.com/demos/images/nature-6.jpg" /></ng-template
      ><ng-template swiperSlide
        ><img
          src="https://swiperjs.com/demos/images/nature-7.jpg" /></ng-template
      ><ng-template swiperSlide
        ><img
          src="https://swiperjs.com/demos/images/nature-8.jpg" /></ng-template
      ><ng-template swiperSlide
        ><img
          src="https://swiperjs.com/demos/images/nature-9.jpg" /></ng-template
      ><ng-template swiperSlide
        ><img src="https://swiperjs.com/demos/images/nature-10.jpg"
      /></ng-template>
    </swiper>
    <swiper
      (swiper)="thumbsSwiper = $event"
      [spaceBetween]="10"
      [slidesPerView]="4"
      [freeMode]="true"
      [watchSlidesProgress]="true"
      class="mySwiper"
    >
      <ng-template swiperSlide
        ><img
          src="https://swiperjs.com/demos/images/nature-1.jpg" /></ng-template
      ><ng-template swiperSlide
        ><img
          src="https://swiperjs.com/demos/images/nature-2.jpg" /></ng-template
      ><ng-template swiperSlide
        ><img
          src="https://swiperjs.com/demos/images/nature-3.jpg" /></ng-template
      ><ng-template swiperSlide
        ><img
          src="https://swiperjs.com/demos/images/nature-4.jpg" /></ng-template
      ><ng-template swiperSlide
        ><img
          src="https://swiperjs.com/demos/images/nature-5.jpg" /></ng-template
      ><ng-template swiperSlide
        ><img
          src="https://swiperjs.com/demos/images/nature-6.jpg" /></ng-template
      ><ng-template swiperSlide
        ><img
          src="https://swiperjs.com/demos/images/nature-7.jpg" /></ng-template
      ><ng-template swiperSlide
        ><img
          src="https://swiperjs.com/demos/images/nature-8.jpg" /></ng-template
      ><ng-template swiperSlide
        ><img
          src="https://swiperjs.com/demos/images/nature-9.jpg" /></ng-template
      ><ng-template swiperSlide
        ><img src="https://swiperjs.com/demos/images/nature-10.jpg"
      /></ng-template>
    </swiper>`,
  styleUrls: ["./app.components.scss"],
  encapsulation: ViewEncapsulation.None,
})
export class AppComponent {
  thumbsSwiper: any;
}

// src/demos/310-thumbs-gallery-loop/svelte/App.svelte
<script>
  import { Swiper, SwiperSlide } from "swiper/svelte";

  // Import Swiper styles
  import "swiper/css";

  import "swiper/css/free-mode";
  import "swiper/css/navigation";
  import "swiper/css/thumbs";

  import "./style.css";

  // import required modules
  import { FreeMode, Navigation, Thumbs } from "swiper";

  let thumbsSwiper = null;

  const setThumbsSwiper = (e) => {
    const [swiper] = e.detail;
    // set Thumbs swiper instance
    setTimeout(() => {
      thumbsSwiper = swiper;
    });
  };
</script>

<Swiper
  style="--swiper-navigation-color: #fff;--swiper-pagination-color: #fff"
  loop={true}
  spaceBetween={10}
  navigation={true}
  thumbs={{ swiper: thumbsSwiper }}
  modules={[FreeMode, Navigation, Thumbs]}
  class="mySwiper2"
>
  <SwiperSlide
    ><img src="https://swiperjs.com/demos/images/nature-1.jpg" /></SwiperSlide
  ><SwiperSlide
    ><img src="https://swiperjs.com/demos/images/nature-2.jpg" /></SwiperSlide
  ><SwiperSlide
    ><img src="https://swiperjs.com/demos/images/nature-3.jpg" /></SwiperSlide
  ><SwiperSlide
    ><img src="https://swiperjs.com/demos/images/nature-4.jpg" /></SwiperSlide
  ><SwiperSlide
    ><img src="https://swiperjs.com/demos/images/nature-5.jpg" /></SwiperSlide
  ><SwiperSlide
    ><img src="https://swiperjs.com/demos/images/nature-6.jpg" /></SwiperSlide
  ><SwiperSlide
    ><img src="https://swiperjs.com/demos/images/nature-7.jpg" /></SwiperSlide
  ><SwiperSlide
    ><img src="https://swiperjs.com/demos/images/nature-8.jpg" /></SwiperSlide
  ><SwiperSlide
    ><img src="https://swiperjs.com/demos/images/nature-9.jpg" /></SwiperSlide
  ><SwiperSlide
    ><img src="https://swiperjs.com/demos/images/nature-10.jpg" /></SwiperSlide
  >
</Swiper>
<Swiper
  on:swiper={setThumbsSwiper}
  loop={true}
  spaceBetween={10}
  slidesPerView={4}
  freeMode={true}
  watchSlidesProgress={true}
  modules={[FreeMode, Navigation, Thumbs]}
  class="mySwiper"
>
  <SwiperSlide
    ><img src="https://swiperjs.com/demos/images/nature-1.jpg" /></SwiperSlide
  ><SwiperSlide
    ><img src="https://swiperjs.com/demos/images/nature-2.jpg" /></SwiperSlide
  ><SwiperSlide
    ><img src="https://swiperjs.com/demos/images/nature-3.jpg" /></SwiperSlide
  ><SwiperSlide
    ><img src="https://swiperjs.com/demos/images/nature-4.jpg" /></SwiperSlide
  ><SwiperSlide
    ><img src="https://swiperjs.com/demos/images/nature-5.jpg" /></SwiperSlide
  ><SwiperSlide
    ><img src="https://swiperjs.com/demos/images/nature-6.jpg" /></SwiperSlide
  ><SwiperSlide
    ><img src="https://swiperjs.com/demos/images/nature-7.jpg" /></SwiperSlide
  ><SwiperSlide
    ><img src="https://swiperjs.com/demos/images/nature-8.jpg" /></SwiperSlide
  ><SwiperSlide
    ><img src="https://swiperjs.com/demos/images/nature-9.jpg" /></SwiperSlide
  ><SwiperSlide
    ><img src="https://swiperjs.com/demos/images/nature-10.jpg" /></SwiperSlide
  >
</Swiper>
