// src/demos/410-virtual-slides/react/src/App.jsx
import React, { useRef, useState } from 'react';
import SwiperCore, { Virtual, Navigation, Pagination } from 'swiper/modules';
import { Swiper, SwiperSlide } from 'swiper/react';

// Import Swiper styles
import 'swiper/css';
import 'swiper/css/pagination';
import 'swiper/css/navigation';

import './styles.css';

// install Virtual module
SwiperCore.use([Virtual, Navigation, Pagination]);

export default function App() {
  const [swiperRef, setSwiperRef] = useState(null);
  const appendNumber = useRef(500);
  const prependNumber = useRef(1);
  // Create array with 500 slides
  const [slides, setSlides] = useState(
    Array.from({ length: 500 }).map((_, index) => `Slide ${index + 1}`)
  );

  const prepend = () => {
    setSlides([
      `Slide ${prependNumber.current - 2}`,
      `Slide ${prependNumber.current - 1}`,
      ...slides,
    ]);
    prependNumber.current = prependNumber.current - 2;
    swiperRef.slideTo(swiperRef.activeIndex + 2, 0);
  };

  const append = () => {
    setSlides([...slides, 'Slide ' + ++appendNumber.current]);
  };

  const slideTo = (index) => {
    swiperRef.slideTo(index - 1, 0);
  };

  return (
    <>
      <Swiper
        onSwiper={setSwiperRef}
        slidesPerView={3}
        centeredSlides={true}
        spaceBetween={30}
        pagination={{
          type: 'fraction',
        }}
        navigation={true}
        virtual
      >
        {slides.map((slideContent, index) => (
          <SwiperSlide key={slideContent} virtualIndex={index}>
            {slideContent}
          </SwiperSlide>
        ))}
      </Swiper>

      <p className="append-buttons">
        <button onClick={() => prepend()} className="prepend-2-slides">
          Prepend 2 Slides
        </button>
        <button onClick={() => slideTo(1)} className="prepend-slide">
          Slide 1
        </button>
        <button onClick={() => slideTo(250)} className="slide-250">
          Slide 250
        </button>
        <button onClick={() => slideTo(500)} className="slide-500">
          Slide 500
        </button>
        <button onClick={() => append()} className="append-slides">
          Append Slide
        </button>
      </p>
    </>
  );
}

// demos/src/static/410-virtual-slides/angular/src/app/app.component.ts
import { Component, ViewEncapsulation, ViewChild } from '@angular/core';
import { SwiperComponent } from 'swiper/angular';

// import Swiper core and required modules
import SwiperCore, { Pagination, Navigation, Virtual } from 'swiper';

// install Swiper modules
SwiperCore.use([Pagination, Navigation, Virtual]);

@Component({
  selector: 'app-swiper-example',
  template: `
    <swiper
      #swiperRef
      [slidesPerView]="3"
      [centeredSlides]="true"
      [spaceBetween]="30"
      [pagination]="{
        type: 'fraction'
      }"
      [navigation]="true"
      [virtual]="true"
      class="mySwiper"
    >
      <ng-template swiperSlide *ngFor="let slide of slides">
        <div>{{ slide }}</div>
      </ng-template>
    </swiper>

    <p class="append-buttons">
      <button (click)="prepend()" class="prepend-2-slides">
        Prepend 2 Slides
      </button>
      <button (click)="slideTo(1)" class="slide-1">Slide 1</button>
      <button (click)="slideTo(250)" class="slide-250">Slide 250</button>
      <button (click)="slideTo(500)" class="slide-500">Slide 500</button>
      <button (click)="append()" class="append-slide">Append Slide</button>
    </p>
  `,
  styleUrls: ['./app.component.scss'],
  encapsulation: ViewEncapsulation.None,
})
export class AppComponent {
  slides = Array.from({ length: 500 }).map((_, index) => `Slide ${index + 1}`);
  @ViewChild('swiperRef', { static: false }) swiperRef?: SwiperComponent;

  appendNumber = 500;
  prependNumber = 1;

  prepend() {
    this.slides = [
      ...['Slide ' + --this.prependNumber, 'Slide ' + --this.prependNumber],
      ...this.slides,
    ];
    this.swiperRef.slideTo(this.swiperRef.activeIndex + 2, 0);
  }

  append() {
    this.slides = [...this.slides, 'Slide ' + ++this.appendNumber];
  }

  slideTo(index: number) {
    this.swiperRef.swiperRef.slideTo(index - 1, 0);
  }
}
